name: Build LaTeX document

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@v0.4
      id: nbgv
    - name: Download tuda_logo.pdf
      run: |
        curl -H "Authorization: token $TOKEN" \
          -H 'Accept: application/vnd.github.v3.raw' \
          --fail-with-body \
          -o ./tuda_logo.pdf \
          -L https://api.github.com/repos/georg-jung/tuda-logo/contents/tuda_logo.pdf?ref=master
      env: 
        TOKEN: ${{ secrets.TUDA_LOGO_FINEGRAINEDACCESSTOKEN }} 
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: src/DEMO-TUDaThesis.tex
        latexmk_use_lualatex: true
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: pdf
        path: src/DEMO-TUDaThesis.pdf
