name: Build LaTeX document

on:
  push

env:
  FILENAME: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@v0.4
      id: nbgv
    - name: Download tuda_logo.pdf
      run: |
        curl -H "Authorization: token $TOKEN" \
          -H 'Accept: application/vnd.github.v3.raw' \
          --fail-with-body \
          -o ./src/tuda_logo.pdf \
          -L https://api.github.com/repos/georg-jung/tuda-logo/contents/tuda_logo.pdf?ref=master
      env:
        TOKEN: ${{ secrets.TUDA_LOGO_FINEGRAINEDACCESSTOKEN }}
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: ${{ env.FILENAME }}.tex
        working_directory: src/
        latexmk_use_lualatex: true
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: log
        path: |
          src/${{ env.FILENAME }}.*
          !**/*.tex
        if-no-files-found: error
        retention-days: 7
    - name: Install exiftool & qpdf
      run: sudo apt-get install -y libimage-exiftool-perl qpdf
    - name: '[exiftool] Add git version properties'
      run: |
        exiftool -config exiftool.cfg -overwrite_original \
          -GitVersion="${{ steps.nbgv.outputs.AssemblyInformationalVersion }}" \
          -GitCommit="${{ steps.nbgv.outputs.GitCommitId }}" \
          src/${{ env.FILENAME }}.pdf
    - name: '[qpdf] Linearize pdf'
      run: qpdf src/${{ env.FILENAME }}.pdf --linearize --replace-input
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: pdf
        path: src/${{ env.FILENAME }}.pdf
        if-no-files-found: error
    - name: Validate PDF/A conformity
      run: ./validate-pdfa.sh src/${{ env.FILENAME }}.pdf


  convert:
    runs-on: ubuntu-latest
    container: pandoc/latex:latest
    steps:
    - uses: actions/checkout@v3
    - run: pandoc --self-contained src/${{ env.FILENAME }}.tex -o ${{ env.FILENAME }}.docx
    - run: pandoc --template=pandoc-htmltemplate.html5 --self-contained src/${{ env.FILENAME }}.tex -o ${{ env.FILENAME }}.html
    - name: Upload docx
      uses: actions/upload-artifact@v3
      with:
        name: docx + html
        path: |
          ${{ env.FILENAME }}.docx
          ${{ env.FILENAME }}.html
        if-no-files-found: error
